#pragma once

#include "color3.h"
#include "color4.h"
#include "mat3_c.h"
#include "mat4_c.h"
#include "swizzle.h"
#include "transform3.h"
#include "vec.h"
#include "vec2.h"
#include "vec3.h"
#include "vec4.h"

#include "impl/color3.inl"
#include "impl/color4.inl"
#include "impl/mat3_c.inl"
#include "impl/mat4_c.inl"
#include "impl/transform3.inl"
#include "impl/vec.inl"
#include "impl/vec2.inl"
#include "impl/vec3.inl"
#include "impl/vec4.inl"
